import { useState, useMemo, useEffect, useCallback } from "react";
import axios from "axios";

/* ════════════════════════════════════════════════════════════════════════════
   AXIOS INSTANCE
════════════════════════════════════════════════════════════════════════════ */
const api = axios.create({
  baseURL:         import.meta.env.VITE_API_URL || "http://localhost:5000/api",
  withCredentials: true,
  headers: { "Content-Type": "application/json" },
});

/* ════════════════════════════════════════════════════════════════════════════
   API CALLS
════════════════════════════════════════════════════════════════════════════ */
const getAdminsAPI = (params) =>
  api.get("/superadmin/admins", { params }).then(r => r.data);

const createAdminAPI = (body) =>
  api.post("/superadmin/admins", body).then(r => r.data);

const toggleStatusAPI = (id) =>
  api.patch(`/superadmin/admins/${id}/status`).then(r => r.data);

const changeAdminPasswordAPI = (id, password, confirmPassword) =>
  api.patch(`/superadmin/admins/${id}/password`, { password, confirmPassword }).then(r => r.data);

/* ════════════════════════════════════════════════════════════════════════════
   CONSTANTS
════════════════════════════════════════════════════════════════════════════ */
// username is auto-generated by backend — removed from form
// masterShare is read from req.user.downlineShare on backend
// adminShare = masterShare - myShare (auto-calculated on backend)
const EMPTY_FORM = {
  firstName:   "",
  masterShare: "",   // superadmin's available share — shown read-only
  myShare:     "",   // what superadmin keeps
  ledgerShare: "",
  fixLimit:    "",
  password:    "",
  confirmPassword: "",
};

const inputCls =
  "w-full border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-800 " +
  "focus:outline-none focus:ring-2 focus:ring-teal-400 focus:border-transparent transition";

const readonlyCls =
  "w-full border border-gray-100 rounded-lg px-3 py-2 text-sm text-gray-400 bg-gray-50 cursor-not-allowed";

/* ════════════════════════════════════════════════════════════════════════════
   SMALL COMPONENTS
════════════════════════════════════════════════════════════════════════════ */
function Icon({ d, size = 14 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d={d} />
    </svg>
  );
}

function Spinner() {
  return (
    <svg className="animate-spin" width="13" height="13" viewBox="0 0 24 24"
      fill="none" stroke="currentColor" strokeWidth="2.5">
      <path d="M21 12a9 9 0 11-6.219-8.56" />
    </svg>
  );
}

function Field({ label, children }) {
  return (
    <div>
      <label className="block text-xs font-semibold text-gray-500 mb-1 uppercase tracking-wide">
        {label}
      </label>
      {children}
    </div>
  );
}

function Modal({ open, title, onClose, children }) {
  if (!open) return null;
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/50"
      onClick={e => e.target === e.currentTarget && onClose()}
    >
      <div className="bg-white rounded-xl shadow-2xl w-[480px] max-w-[95vw] p-6 max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between mb-5">
          <h2 className="text-lg font-bold text-gray-800">{title}</h2>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <Icon d="M18 6L6 18M6 6l12 12" size={18} />
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

/* ════════════════════════════════════════════════════════════════════════════
   MAIN PAGE
════════════════════════════════════════════════════════════════════════════ */
export default function AdminsPage() {
  /* ── State ── */
  const [admins, setAdmins]         = useState([]);
  const [loading, setLoading]       = useState(false);
  const [search, setSearch]         = useState("");
  const [page, setPage]             = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [sortKey, setSortKey]       = useState("username");
  const [sortAsc, setSortAsc]       = useState(true);

  // superadmin's own downlineShare fetched once on mount
  const [myDownlineShare, setMyDownlineShare] = useState(100);

  // create modal
  const [modalOpen, setModalOpen] = useState(false);
  const [saving, setSaving]       = useState(false);
  const [form, setForm]           = useState(EMPTY_FORM);

  // change password modal
  const [passOpen, setPassOpen]       = useState(false);
  const [passId, setPassId]           = useState(null);
  const [newPass, setNewPass]         = useState("");
  const [confirmPass, setConfirmPass] = useState("");
  const [passLoading, setPassLoading] = useState(false);

  // toast
  const [toast, setToast] = useState(null);
  const showToast = useCallback((msg, err = false) => {
    setToast({ msg, err });
    setTimeout(() => setToast(null), 2500);
  }, []);

  /* ── Derived: adminShare shown live in form ── */
  const adminShare = useMemo(() => {
    const master = Number(form.masterShare);
    const ms     = Number(form.myShare);
    if (isNaN(master) || isNaN(ms) || form.masterShare === "" || form.myShare === "") return "";
    const result = master - ms;
    return result < 0 ? "Invalid" : result;
  }, [form.masterShare, form.myShare]);

  /* ── Open create modal: pre-fill masterShare from superadmin's budget ── */
  const openCreateModal = () => {
    setForm({ ...EMPTY_FORM, masterShare: String(myDownlineShare) });
    setModalOpen(true);
  };

  /* ── Fetch admins ── */
  const fetchAdmins = useCallback(async () => {
    setLoading(true);
    try {
      const res = await getAdminsAPI({ page, limit: 10, search });
      // backend returns: { success, count, data: [...] }
      setAdmins(res.data ?? []);
      setTotalPages(res.pagination?.totalPages ?? 1);
    } catch (err) {
      showToast(err?.response?.data?.message ?? err.message, true);
    } finally {
      setLoading(false);
    }
  }, [page, search, showToast]);

  useEffect(() => { fetchAdmins(); }, [fetchAdmins]);
  useEffect(() => { setPage(1); }, [search]);

  /* ── Client-side sort ── */
  const rows = useMemo(() =>
    [...admins].sort((a, b) => {
      const av = a[sortKey], bv = b[sortKey];
      const r = typeof av === "number" ? av - bv : String(av ?? "").localeCompare(String(bv ?? ""));
      return sortAsc ? r : -r;
    }),
    [admins, sortKey, sortAsc]
  );

  const handleSort = key => {
    if (sortKey === key) setSortAsc(p => !p);
    else { setSortKey(key); setSortAsc(true); }
  };

  /* ── Create admin ── */
  const handleCreate = async () => {
    const master = Number(form.masterShare);
    const ms     = Number(form.myShare);
    const ls     = Number(form.ledgerShare || 0);
    const fl     = Number(form.fixLimit    || 0);

    // Client-side validation
    if (!form.password.trim())
      return showToast("Password is required", true);
    if (form.password !== form.confirmPassword)
      return showToast("Passwords do not match", true);
    if (form.password.length < 6)
      return showToast("Password must be at least 6 characters", true);
    if (form.myShare === "")
      return showToast("My Share is required", true);
    if (ms > master)
      return showToast(`My Share (${ms}) cannot exceed Master Share (${master})`, true);
    if (adminShare === "Invalid" || adminShare < 0)
      return showToast("Admin Share cannot be negative — reduce My Share", true);

    setSaving(true);
    try {
      const res = await createAdminAPI({
        firstName:   form.firstName.trim(),
        masterShare: master,
        myShare:     ms,
        ledgerShare: ls,
        fixLimit:    fl,
        password:         form.password,
        confirmPassword:  form.confirmPassword,
      });
      showToast(res.message ?? "Admin created successfully");
      setModalOpen(false);
      setForm(EMPTY_FORM);
      fetchAdmins();
    } catch (err) {
      showToast(err?.response?.data?.message ?? err.message, true);
    } finally {
      setSaving(false);
    }
  };

  /* ── Toggle block/unblock ── */
  const handleToggle = async (id) => {
    try {
      const res = await toggleStatusAPI(id);
      showToast(res.message);
      // Optimistic update — no refetch needed
      setAdmins(p => p.map(a => a._id === id ? { ...a, isActive: res.data.isActive } : a));
    } catch (err) {
      showToast(err?.response?.data?.message ?? err.message, true);
    }
  };

  /* ── Change password ── */
  const openPassModal = id => {
    setPassId(id);
    setNewPass("");
    setConfirmPass("");
    setPassOpen(true);
  };

  const handleChangePassword = async () => {
    if (!newPass)                  return showToast("Enter a new password", true);
    if (newPass.length < 6)        return showToast("Password must be at least 6 characters", true);
    if (newPass !== confirmPass)   return showToast("Passwords don't match", true);

    setPassLoading(true);
    try {
      // backend requires both password + confirmPassword
      const res = await changeAdminPasswordAPI(passId, newPass, confirmPass);
      showToast(res.message || "Password updated");
      setPassOpen(false);
    } catch (err) {
      showToast(err?.response?.data?.message ?? err.message, true);
    } finally {
      setPassLoading(false);
    }
  };

  /* ── Table header ── */
  const Th = ({ label, k }) => (
    <th
      onClick={() => k && handleSort(k)}
      className={`px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase
        tracking-wider border border-gray-200 bg-gray-50 whitespace-nowrap
        ${k ? "cursor-pointer select-none hover:bg-gray-100" : ""}`}
    >
      {label}
      {k && (
        <span className={`ml-1 text-xs ${sortKey === k ? "text-teal-600" : "text-gray-400"}`}>
          {sortKey === k ? (sortAsc ? "↑" : "↓") : "↕"}
        </span>
      )}
    </th>
  );

  /* ════════════════════════════════════════════════════════════════════════
     RENDER
  ════════════════════════════════════════════════════════════════════════ */
  return (
    <>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap');
        * { font-family: 'DM Sans', sans-serif; }`}
      </style>

      <div className="min-h-screen bg-gray-100 p-4 sm:p-6">
        <div className="max-w-7xl mx-auto">

          <h1 className="text-2xl font-bold text-gray-800 mb-5">Admins</h1>

          <div className="bg-white rounded-xl shadow-sm border border-gray-200">

            {/* ── Toolbar ── */}
            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-200 flex-wrap gap-3">
              <div className="flex items-center gap-2 ml-auto">
                <span className="text-sm text-gray-500">Search:</span>
                <input
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                  placeholder="Username…"
                  className="border border-gray-200 rounded px-3 py-1.5 text-sm text-gray-700
                    focus:outline-none focus:ring-2 focus:ring-teal-400 w-44"
                />
              </div>
              <button
                onClick={openCreateModal}
                className="flex items-center gap-2 bg-teal-500 hover:bg-teal-600 text-white
                  font-semibold text-sm px-4 py-2 rounded-lg transition-colors shadow-sm"
              >
                <Icon d="M12 5v14M5 12h14" size={14} />
                Create Admin
              </button>
            </div>

            {/* ── Table ── */}
            <div className="overflow-x-auto">
              <table className="w-full border-collapse text-sm">
                <thead>
                  <tr>
                    <Th label="Sr. No."       k={null} />
                    <Th label="Username"      k="username" />
                    <Th label="Name"          k="firstName" />
                    <Th label="Ledger Share"  k="ledgerShare" />
                    <Th label="My Share %"    k="myShare" />
                    <Th label="Admin Share %" k="downlineShare" />
                    <Th label="Status"        k="isActive" />
                    <Th label="Action"        k={null} />
                  </tr>
                </thead>
                <tbody>
                  {loading ? (
                    <tr>
                      <td colSpan={8} className="px-4 py-10 text-center text-gray-400 text-sm">
                        <span className="inline-flex items-center gap-2">
                          <Spinner /> Loading admins…
                        </span>
                      </td>
                    </tr>
                  ) : rows.length === 0 ? (
                    <tr>
                      <td colSpan={8} className="px-4 py-10 text-center text-gray-400 text-sm">
                        No admins found.
                      </td>
                    </tr>
                  ) : (
                    rows.map((a, i) => (
                      <tr key={a._id} className="hover:bg-gray-50 transition-colors">
                        <td className="px-4 py-3 border border-gray-100 text-gray-500 text-center">
                          {(page - 1) * 10 + i + 1}
                        </td>
                        <td className="px-4 py-3 border border-gray-100 font-medium text-gray-800">
                          {a.username?.toUpperCase()}
                        </td>
                        <td className="px-4 py-3 border border-gray-100 text-gray-600">
                          {a.firstName || "—"}
                        </td>
                        <td className="px-4 py-3 border border-gray-100 text-gray-700 text-right">
                          {(a.ledgerShare ?? 0).toFixed(2)}
                        </td>
                        <td className="px-4 py-3 border border-gray-100 text-gray-700 text-right">
                          {(a.myShare ?? 0).toFixed(2)}
                        </td>
                        <td className="px-4 py-3 border border-gray-100 text-gray-700 text-right">
                          {(a.downlineShare ?? 0).toFixed(2)}
                        </td>
                        <td className="px-4 py-3 border border-gray-100">
                          {a.isActive ? (
                            <span className="inline-flex items-center gap-1.5 bg-teal-500 text-white text-xs font-semibold px-3 py-1 rounded">
                              <Icon d="M20 6L9 17l-5-5" size={11} /> Active
                            </span>
                          ) : (
                            <span className="inline-flex items-center gap-1.5 bg-red-500 text-white text-xs font-semibold px-3 py-1 rounded">
                              <Icon d="M18 6L6 18M6 6l12 12" size={11} /> Blocked
                            </span>
                          )}
                        </td>
                        <td className="px-4 py-3 border border-gray-100">
                          <div className="flex items-center gap-2 flex-wrap">
                            <button
                              onClick={() => handleToggle(a._id)}
                              className={`flex items-center gap-1.5 text-white text-xs font-semibold
                                px-3 py-1.5 rounded transition-colors
                                ${a.isActive
                                  ? "bg-red-500 hover:bg-red-600"
                                  : "bg-green-500 hover:bg-green-600"}`}
                            >
                              <Icon d={a.isActive ? "M18 6L6 18M6 6l12 12" : "M20 6L9 17l-5-5"} size={11} />
                              {a.isActive ? "Block" : "Unblock"}
                            </button>
                            <button
                              onClick={() => openPassModal(a._id)}
                              className="flex items-center gap-1.5 bg-teal-600 hover:bg-teal-700
                                text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors whitespace-nowrap"
                            >
                              <Icon d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" size={11} />
                              Change Password
                            </button>
                          </div>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            {/* ── Pagination ── */}
            {totalPages > 1 && (
              <div className="flex items-center justify-center gap-2 px-5 py-4 border-t border-gray-100">
                <button
                  disabled={page === 1}
                  onClick={() => setPage(p => p - 1)}
                  className="px-3 py-1.5 text-sm text-gray-500 hover:text-gray-800
                    disabled:opacity-30 disabled:cursor-not-allowed"
                >
                  &lt;
                </button>
                {Array.from({ length: totalPages }, (_, i) => i + 1).map(p => (
                  <button
                    key={p}
                    onClick={() => setPage(p)}
                    className={`w-8 h-8 text-sm rounded font-medium transition-colors
                      ${page === p ? "bg-teal-500 text-white" : "text-gray-600 hover:bg-gray-100"}`}
                  >
                    {p}
                  </button>
                ))}
                <button
                  disabled={page === totalPages}
                  onClick={() => setPage(p => p + 1)}
                  className="px-3 py-1.5 text-sm text-gray-500 hover:text-gray-800
                    disabled:opacity-30 disabled:cursor-not-allowed"
                >
                  &gt;
                </button>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* ════════════════════════════════════════════════════════════════════
          CREATE ADMIN MODAL
      ════════════════════════════════════════════════════════════════════ */}
      <Modal open={modalOpen} title="Create Admin" onClose={() => setModalOpen(false)}>
        <div className="grid grid-cols-2 gap-4">

          {/* First Name */}
          <div className="col-span-2">
            <Field label="First Name">
              <input className={inputCls} placeholder="Akash" value={form.firstName}
                onChange={e => setForm(p => ({ ...p, firstName: e.target.value }))} />
            </Field>
          </div>

          {/* Username — auto-generated, shown as info */}
          <div className="col-span-2">
            <div className="flex items-center gap-2 bg-teal-50 border border-teal-100 rounded-lg px-3 py-2">
              <Icon d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" size={14} />
              <span className="text-xs text-teal-700 font-medium">
                Username will be auto-generated (e.g. ADMIN693)
              </span>
            </div>
          </div>

          {/* Master Share — read-only, is superadmin's downlineShare */}
          <Field label="Master Share % (Your Budget)">
            <input className={readonlyCls} type="number" readOnly
              value={form.masterShare}
              title="This is your available downline share — cannot be changed here" />
          </Field>

          {/* My Share */}
          <Field label="My Share %">
            <input className={inputCls} type="number" placeholder="0" value={form.myShare}
              min={0} max={Number(form.masterShare)}
              onChange={e => setForm(p => ({ ...p, myShare: e.target.value }))} />
          </Field>

          {/* Admin Share — auto-calculated, read-only */}
          <Field label="Admin Share % (Auto)">
            <input
              className={readonlyCls}
              type="number"
              readOnly
              value={adminShare}
              title="Auto-calculated: Master Share − My Share"
            />
          </Field>

          {/* Ledger Share */}
          <Field label="Ledger Share">
            <input className={inputCls} type="number" placeholder="0" value={form.ledgerShare}
              min={0} max={100}
              onChange={e => setForm(p => ({ ...p, ledgerShare: e.target.value }))} />
          </Field>

          {/* Fix Limit */}
          <Field label="Fix Limit">
            <input className={inputCls} type="number" placeholder="0" value={form.fixLimit}
              min={0}
              onChange={e => setForm(p => ({ ...p, fixLimit: e.target.value }))} />
          </Field>

          {/* Password */}
          <Field label="Password">
            <input className={inputCls} type="password" placeholder="••••••" value={form.password}
              onChange={e => setForm(p => ({ ...p, password: e.target.value }))} />
          </Field>

          {/* Confirm Password */}
          <Field label="Confirm Password">
            <input className={inputCls} type="password" placeholder="••••••" value={form.confirmPassword}
              onChange={e => setForm(p => ({ ...p, confirmPassword: e.target.value }))} />
          </Field>

        </div>

        {/* Live share breakdown */}
        <div className="mt-4 bg-gray-50 border border-gray-100 rounded-lg px-4 py-3 text-xs text-gray-500 space-y-1">
          <div className="flex justify-between">
            <span>Master Share</span>
            <span className="font-semibold text-gray-700">{form.masterShare || 0}%</span>
          </div>
          <div className="flex justify-between">
            <span>− My Share</span>
            <span className="font-semibold text-gray-700">{form.myShare || 0}%</span>
          </div>
          <div className="border-t border-gray-200 pt-1 flex justify-between">
            <span>= Admin Share</span>
            <span className={`font-bold ${adminShare === "Invalid" ? "text-red-500" : "text-teal-600"}`}>
              {adminShare === "" ? "—" : `${adminShare}%`}
            </span>
          </div>
        </div>

        <div className="flex justify-end gap-3 mt-5">
          <button
            onClick={() => setModalOpen(false)}
            className="px-4 py-2 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleCreate}
            disabled={saving || adminShare === "Invalid"}
            className="flex items-center gap-2 px-5 py-2 text-sm font-semibold
              bg-teal-500 hover:bg-teal-600 disabled:opacity-60 text-white rounded-lg transition-colors"
          >
            {saving && <Spinner />}
            {saving ? "Creating…" : "Create Admin"}
          </button>
        </div>
      </Modal>

      {/* ════════════════════════════════════════════════════════════════════
          CHANGE PASSWORD MODAL
      ════════════════════════════════════════════════════════════════════ */}
      <Modal open={passOpen} title="Change Password" onClose={() => setPassOpen(false)}>
        <div className="flex flex-col gap-4">
          <Field label="New Password">
            <input className={inputCls} type="password" placeholder="Enter new password"
              value={newPass} onChange={e => setNewPass(e.target.value)} />
          </Field>
          <Field label="Confirm Password">
            <input className={inputCls} type="password" placeholder="Confirm password"
              value={confirmPass} onChange={e => setConfirmPass(e.target.value)} />
          </Field>
        </div>
        <div className="flex justify-end gap-3 mt-6">
          <button
            onClick={() => setPassOpen(false)}
            className="px-4 py-2 text-sm text-gray-600 border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={handleChangePassword}
            disabled={passLoading}
            className="flex items-center gap-2 px-5 py-2 text-sm font-semibold
              bg-teal-500 hover:bg-teal-600 disabled:opacity-60 text-white rounded-lg transition-colors"
          >
            {passLoading && <Spinner />}
            {passLoading ? "Updating…" : "Update Password"}
          </button>
        </div>
      </Modal>

      {/* ── Toast ── */}
      {toast && (
        <div className={`fixed bottom-6 right-6 px-5 py-3 rounded-xl text-sm font-semibold
          shadow-xl z-[200] text-white ${toast.err ? "bg-red-500" : "bg-teal-500"}`}>
          {toast.msg}
        </div>
      )}
    </>
  );
}